// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Nama   string `json:"nama"`
	Umur   int    `json:"umur"`
	Alamat string `json:"alamat"`
}

type User struct {
	UUID       string `json:"uuid"`
	Nama       string `json:"nama"`
	Umur       int    `json:"umur"`
	Alamat     string `json:"alamat"`
	Searchable string `json:"searchable"`
}
